package com.jk.cashcontrol.presentation.statistics

data class StatisticsState(
    val todayIncome : Float = 0f,
    val todayExpense : Float = 0f,
    val thisMonthIncome : Float = 0f,
    val thisMonthExpense : Float = 0f,
    val thisYearIncome : Float = 0f,
    val thisYearExpense : Float = 0f,
    val todayTopIncomeCategory: String = "Other",
    val todayTopExpenseCategory: String = "Other",
    val thisMonthTopIncomeCategory: String = "Other",
    val thisMonthTopExpenseCategory: String = "Other",
    val thisYearTopIncomeCategory: String = "Other",
    val thisYearTopExpenseCategory: String = "Other",
    val isTodaySummaryGenerated : Boolean = false,
    val todayGeneratedSummary : String = "",
    val isThisMonthSummaryGenerated : Boolean = false,
    val thisMonthGeneratedSummary : String = "",
    val isThisYearSummaryGenerated : Boolean = false,
    val thisYearGeneratedSummary : String = "",
    val isTodaySummaryLoading : Boolean = false,
    val isThisMonthSummaryLoading : Boolean = false,
    val isThisYearSummaryLoading : Boolean = false,
)
